### ISSUE TITLE
Multi-inheritance 

### ISSUE THREAD

**Issue by OGKevin** [PJUllrich/Complete-Bunq-API-Python-Wrapper#2]
Found a multi-inheritance error

In the [payment] endpoint:

```python
class Payment(MonetaryAccount):
      pass
```

In the [request-inquiry] endpoint:

```python
class RequestInquiry(MonetaryAccount, Payment):
  pass

```

Should be:

```python
class RequestInquiry(Payment):
  pass

```
[payment]:<https://github.com/PJUllrich/Complete-Bunq-API-Python-Wrapper/blob/af5d3c8d2f3e0512c2aee556f1dde75e2e9d710c/endpoints/payment.py#L4>
[request-inquiry]:<https://github.com/PJUllrich/Complete-Bunq-API-Python-Wrapper/blob/0e28d63c77888f102bd2a4cd9a3610890e1dc70b/apiwrapper/endpoints/request_inquiry.py#L6>

**Comment by PJUllrich** [comment]
Thanks, I will fix it with the next commit.

**Comment by PJUllrich** [comment]
Fixed in [this commit](https://github.com/PJUllrich/Complete-Bunq-API-Python-Wrapper/commit/01543cf190ae8604ade710f0809f25822c69bcdc)

**Comment by OGKevin** [comment]
💪
